---
timelines:
  variableUpdate:
  - EnvironmentObject
  
  - Rhythm
  - Items

  - GameState
  - Move
  - Particle

  - SpriteAnimation
  - Camera
  - UI

  render:
  - SpriteRender
  - CameraRender
  - RhythmRender
  - UIRender
...
