---

type:
  name: PainterService
  include: "src/services/painter_service.h"

---

type:
  name: InputService
  include: "src/services/input_service.h"

---

type:
  name: RhythmService
  include: "src/services/rhythm_service.h"

...