---

items:
  - id: sword
    imageBroken: items/sword_broken.png
    imageFixed: items/sword_fixed.png
    actions: "AAAB"
  - id: helmet
    imageBroken: items/helmet_broken.png
    imageFixed: items/helmet_fixed.png
    actions: "YYYB"
  - id: knife
    imageBroken: items/knife_broken.png
    imageFixed: items/knife_broken.png
    actions: "XYYB"
  - id: laptop
    imageBroken: items/laptop_fixed.png
    imageFixed: items/laptop_fixed.png
    actions: "XAXB"
  - id: dog
    imageBroken: items/dog_fixed.png
    imageFixed: items/dog_fixed.png
    actions: "BBBB"
  - id: pizza
    imageBroken: items/pizza_broken.png
    imageFixed: items/pizza_fixed.png
    actions: "YXYB"
  - id: cow
    imageBroken: items/cow_broken.png
    imageFixed: items/cow_fixed.png
    actions: "AYBB"

...